//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AHD.ID3.Editor.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.0.3.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("27, 13")]
        public global::System.Drawing.Point Win_Location {
            get {
                return ((global::System.Drawing.Point)(this["Win_Location"]));
            }
            set {
                this["Win_Location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1081, 644")]
        public global::System.Drawing.Size Win_Size {
            get {
                return ((global::System.Drawing.Size)(this["Win_Size"]));
            }
            set {
                this["Win_Size"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("207")]
        public int SplitContainer1 {
            get {
                return ((int)(this["SplitContainer1"]));
            }
            set {
                this["SplitContainer1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("521")]
        public int SplitContainer2 {
            get {
                return ((int)(this["SplitContainer2"]));
            }
            set {
                this["SplitContainer2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("331")]
        public int SplitContainer3 {
            get {
                return ((int)(this["SplitContainer3"]));
            }
            set {
                this["SplitContainer3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("330")]
        public int SplitContainer4 {
            get {
                return ((int)(this["SplitContainer4"]));
            }
            set {
                this["SplitContainer4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("317")]
        public int SplitContainer5 {
            get {
                return ((int)(this["SplitContainer5"]));
            }
            set {
                this["SplitContainer5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::AHD.ID3.Editor.LayoutPresent DefaultLayout {
            get {
                return ((global::AHD.ID3.Editor.LayoutPresent)(this["DefaultLayout"]));
            }
            set {
                this["DefaultLayout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FirstRun {
            get {
                return ((bool)(this["FirstRun"]));
            }
            set {
                this["FirstRun"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::AHD.ID3.Editor.Base.ColumnsManager ColumnsManager {
            get {
                return ((global::AHD.ID3.Editor.Base.ColumnsManager)(this["ColumnsManager"]));
            }
            set {
                this["ColumnsManager"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection GenreMemory {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["GenreMemory"]));
            }
            set {
                this["GenreMemory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection ArtistsMemory {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ArtistsMemory"]));
            }
            set {
                this["ArtistsMemory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection AlbumsMemory {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["AlbumsMemory"]));
            }
            set {
                this["AlbumsMemory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int DoubleClickActionIndex {
            get {
                return ((int)(this["DoubleClickActionIndex"]));
            }
            set {
                this["DoubleClickActionIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int DefaultID3V2Version {
            get {
                return ((int)(this["DefaultID3V2Version"]));
            }
            set {
                this["DefaultID3V2Version"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ID3V2_UseUnsynchronisation {
            get {
                return ((bool)(this["ID3V2_UseUnsynchronisation"]));
            }
            set {
                this["ID3V2_UseUnsynchronisation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ID3V2_KeepPadding {
            get {
                return ((bool)(this["ID3V2_KeepPadding"]));
            }
            set {
                this["ID3V2_KeepPadding"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ID3V2_DropExtendedHeader {
            get {
                return ((bool)(this["ID3V2_DropExtendedHeader"]));
            }
            set {
                this["ID3V2_DropExtendedHeader"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ID3V2_WriteFooter {
            get {
                return ((bool)(this["ID3V2_WriteFooter"]));
            }
            set {
                this["ID3V2_WriteFooter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MediaPlayerAutoStart {
            get {
                return ((bool)(this["MediaPlayerAutoStart"]));
            }
            set {
                this["MediaPlayerAutoStart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Silver")]
        public global::System.Drawing.Color TabPageColor {
            get {
                return ((global::System.Drawing.Color)(this["TabPageColor"]));
            }
            set {
                this["TabPageColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LightGoldenrodYellow")]
        public global::System.Drawing.Color TabPageHighlightColor {
            get {
                return ((global::System.Drawing.Color)(this["TabPageHighlightColor"]));
            }
            set {
                this["TabPageHighlightColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color TabPageSelectColor {
            get {
                return ((global::System.Drawing.Color)(this["TabPageSelectColor"]));
            }
            set {
                this["TabPageSelectColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LightGray")]
        public global::System.Drawing.Color TabPageSplitcolor {
            get {
                return ((global::System.Drawing.Color)(this["TabPageSplitcolor"]));
            }
            set {
                this["TabPageSplitcolor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color TabPageTextColor {
            get {
                return ((global::System.Drawing.Color)(this["TabPageTextColor"]));
            }
            set {
                this["TabPageTextColor"] = value;
            }
        }
    }
}
